### ISSUE TITLE
UI menus and the addition of "settings"

### ISSUE THREAD

**Issue by chynnasevilleno** [chynnasevilleno/SAD-Enrollment#3]
Hello team. I recently made a commit on ma'am cindy's requests on the ff:
- change specific menus into one "settings" (eg. from Student Profiles -> sa Settings nalang sya makita. zzz hard to explain)
- merge EVERYTHING into one menu for settings and a diff menu for ALL reports

I would like to ask for your opinions on the ff:
- layout of the settings page. i feel like it's bad UX to add two links so close to each other (i mean who has time to read everything just to find what they need zzz)
- should i only add "Student Profiles" to imply na that's to view the student profiles list and then duon na ang add student profile? since user process is probably: look up student profile -> if wala, then add student profile -> if meron, click on it to view transactions or details.

<img width="1279" alt="IT LOOKS SO HORRIBLE" src="https://user-images.githubusercontent.com/23465350/34307060-41272d7c-e781-11e7-9ce3-451184023a58.png">

**Comment by aaajii** [comment]
## UX Suggestion on links:
We can remove the view lists and make the header click-able itself where it displays the table if it's clicked, and place a simple add button because thats what the user would likely use when checking out the settings tab. (Concept from django-admin dashboard).  *Not explicitly following the design*, but we can take the from concept there.

![image](https://user-images.githubusercontent.com/27285268/34466684-c1316f80-ef17-11e7-8e1f-d86a1bc6ade9.png)

*show list after clicking the header* (nevermind the "died" column this was from a project of mine)

![image](https://user-images.githubusercontent.com/27285268/34520655-8beb1b42-f0c4-11e7-96e7-651d47ee6c72.png)



### Side-comments
Not sure if the word "Settings" is the best term used here, i suggest changing the term that's more applicable to the function of the page while being user-friendly.

**Comment by coleenyuson** [comment]
Yep! I agree with Jim's suggestion. I think it's better to design it that way.

**Comment by aaajii** [comment]
![image](https://user-images.githubusercontent.com/27285268/34520572-2a80da7c-f0c4-11e7-8690-f4e55e5ec1f7.png)
EHEAuehueuHEUHE
